# Generated by Django 4.1.3 on 2022-11-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "Ciudad", "verbose_name_plural": "Ciudades"},
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "Ubicación", "verbose_name_plural": "Ubicaciones"},
        ),
        migrations.AlterModelOptions(
            name="warehouse",
            options={"verbose_name": "Bodega", "verbose_name_plural": "Bodegas"},
        ),
    ]
