# Generated by Django 4.1.3 on 2022-11-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wood", "0002_product_city"),
        ("warehouse", "0002_alter_city_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="products",
            field=models.ManyToManyField(
                through="wood.Product_City", to="wood.product"
            ),
        ),
    ]
