# Generated by Django 4.1.3 on 2022-11-25 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0003_city_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="warehouse_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="warehouse.warehouse"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="map_url",
            field=models.ImageField(
                default="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPIHJQ_j5byp-SD9Is88D6h-a72knRe_YS4Q&usqp=CAU",
                upload_to="maps",
            ),
        ),
    ]
