# Generated by Django 4.1.3 on 2022-11-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_location_warehouse_id_alter_warehouse_map_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': '3.1 Ciudad', 'verbose_name_plural': '3.1 Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': '3.3 Ubicación', 'verbose_name_plural': '3.3 Ubicaciones'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': '3.2 Bodega', 'verbose_name_plural': '3.2 Bodegas'},
        ),
        migrations.AlterField(
            model_name='city',
            name='code',
            field=models.CharField(max_length=36, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.CharField(max_length=256, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='location',
            name='warehouse_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.warehouse', verbose_name='Bodega'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(max_length=36, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='map_url',
            field=models.ImageField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPIHJQ_j5byp-SD9Is88D6h-a72knRe_YS4Q&usqp=CAU', upload_to='maps', verbose_name='Mapa guía'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
