# Generated by Django 4.1.3 on 2022-11-22 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_alter_employee_options_alter_provider_options_and_more"),
        ("warehouse", "0002_alter_city_options_alter_location_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Tipo de inventario",
                "verbose_name_plural": "Tipos de inventario",
            },
        ),
        migrations.CreateModel(
            name="Line",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
            ],
            options={
                "verbose_name": "Familia",
                "verbose_name_plural": "Familias",
            },
        ),
        migrations.CreateModel(
            name="Wood_State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
            ],
            options={
                "verbose_name": "Estado de madera",
                "verbose_name_plural": "Estados de madera",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("code", models.CharField(max_length=32)),
                ("is_wood", models.BooleanField(default=False)),
                ("length", models.DecimalField(decimal_places=2, max_digits=8)),
                ("width", models.DecimalField(decimal_places=2, max_digits=8)),
                ("height", models.DecimalField(decimal_places=2, max_digits=8)),
                ("species", models.CharField(max_length=256)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "inventory_type_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wood.inventory_type",
                    ),
                ),
                (
                    "line_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wood.line"
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="Kit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "destiny_location_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="destiny",
                        to="warehouse.location",
                    ),
                ),
                (
                    "employee_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.employee",
                    ),
                ),
                (
                    "external_provider_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="user.provider",
                    ),
                ),
                (
                    "location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="current",
                        to="warehouse.location",
                    ),
                ),
                (
                    "original_location_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="original",
                        to="warehouse.location",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wood.product"
                    ),
                ),
                (
                    "state_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="wood.wood_state",
                    ),
                ),
                (
                    "updating_user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="user.user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kit",
                "verbose_name_plural": "Kits",
            },
        ),
    ]
