# Generated by Django 4.1.3 on 2022-11-22 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0002_alter_city_options_alter_location_options_and_more"),
        ("wood", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="warehouse.city"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="wood.product"
                    ),
                ),
            ],
        ),
    ]
