# Generated by Django 4.1.3 on 2022-11-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wood", "0002_product_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product_city",
            options={
                "verbose_name": "Asignación",
                "verbose_name_plural": "Asignaciones",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="height",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="length",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="species",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="width",
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
