# Generated by Django 4.1.3 on 2022-11-27 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("warehouse", "0004_alter_location_warehouse_id_alter_warehouse_map_url"),
        ("user", "0003_alter_user_photo_url"),
        ("wood", "0004_alter_kit_original_location_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="destiny_location_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="destiny",
                to="warehouse.location",
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="employee_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.employee",
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="external_provider_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.provider",
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="original_location_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="original",
                to="warehouse.location",
            ),
        ),
    ]
