# Generated by Django 4.1.3 on 2022-11-27 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wood", "0005_alter_kit_destiny_location_id_alter_kit_employee_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kit",
            name="product_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="wood.product",
                verbose_name="Producto",
            ),
        ),
    ]
