# Generated by Django 4.1.3 on 2022-11-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_city_options_alter_location_options_and_more'),
        ('user', '0004_alter_employee_options_alter_provider_options_and_more'),
        ('wood', '0006_alter_kit_product_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory_type',
            options={'verbose_name': '2.4 Tipo de inventario', 'verbose_name_plural': '2.4 Tipos de inventario'},
        ),
        migrations.AlterModelOptions(
            name='kit',
            options={'verbose_name': '2.3 Kit', 'verbose_name_plural': '2.3 Kits'},
        ),
        migrations.AlterModelOptions(
            name='line',
            options={'verbose_name': '2.1 Línea', 'verbose_name_plural': '2.1 Líneas'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '2.2 Producto', 'verbose_name_plural': '2.2 Productos'},
        ),
        migrations.AlterModelOptions(
            name='product_city',
            options={'verbose_name': '2.6 Asignación de Producto a ciudad', 'verbose_name_plural': '2.6 Asignación de Productos a ciudades'},
        ),
        migrations.AlterModelOptions(
            name='wood_state',
            options={'verbose_name': '2.5 Estado de madera', 'verbose_name_plural': '2.5 Estados de madera'},
        ),
        migrations.AlterField(
            model_name='inventory_type',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='destiny_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destiny', to='warehouse.location', verbose_name='Ubicación de destino'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.employee', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='external_provider_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.provider', verbose_name='Proveedor externo'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='location_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current', to='warehouse.location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='original_location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='original', to='warehouse.location', verbose_name='Ubicación de origen'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.wood_state', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='updating_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.user', verbose_name='Usuario de última actualización'),
        ),
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=32, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Alto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.inventory_type', verbose_name='Tipo de inventario'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_wood',
            field=models.BooleanField(default=False, verbose_name='¿Es madera?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.line', verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='species',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ancho'),
        ),
        migrations.AlterField(
            model_name='product_city',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.city', verbose_name='Ciudad con existencia de producto'),
        ),
        migrations.AlterField(
            model_name='product_city',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wood.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='wood_state',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Nombre'),
        ),
    ]
