# Generated by Django 4.1.3 on 2022-11-28 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wood", "0007_alter_inventory_type_options_alter_kit_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventory_type",
            options={
                "verbose_name": "Tipo de inventario",
                "verbose_name_plural": "2.4 Tipos de inventario",
            },
        ),
        migrations.AlterModelOptions(
            name="kit",
            options={"verbose_name": "Kit", "verbose_name_plural": "2.3 Kits"},
        ),
        migrations.AlterModelOptions(
            name="line",
            options={"verbose_name": "Línea", "verbose_name_plural": "2.1 Líneas"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "2.2 Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="product_city",
            options={
                "verbose_name": "Asignación de Producto a ciudad",
                "verbose_name_plural": "2.6 Asignación de Productos a ciudades",
            },
        ),
        migrations.AlterModelOptions(
            name="wood_state",
            options={
                "verbose_name": "Estado de madera",
                "verbose_name_plural": "2.5 Estados de madera",
            },
        ),
        migrations.AddField(
            model_name="kit",
            name="transformed_at_datettime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de utilización total"
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="transformed_into_kit_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wood.kit",
            ),
        ),
        migrations.AddField(
            model_name="kit",
            name="used_at_datettime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de utilización total"
            ),
        ),
    ]
