# Generated by Django 4.1.3 on 2022-11-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wood", "0008_alter_inventory_type_options_alter_kit_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kit",
            old_name="transformed_at_datettime",
            new_name="transformed_at_datetime",
        ),
        migrations.RenameField(
            model_name="kit",
            old_name="used_at_datettime",
            new_name="used_at_datetime",
        ),
    ]
