# Generated by Django 4.1.3 on 2022-11-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "wood",
            "0009_rename_transformed_at_datettime_kit_transformed_at_datetime_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="kit",
            name="transformed_into_kit_id",
        ),
        migrations.AddField(
            model_name="kit",
            name="source_kit_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="wood.kit",
                verbose_name="Kit materia prima",
            ),
        ),
        migrations.AlterField(
            model_name="kit",
            name="transformed_at_datetime",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de transformación"
            ),
        ),
    ]
