# Generated by Django 4.1.3 on 2022-11-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={"verbose_name": "Empleado", "verbose_name_plural": "Empleados"},
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={"verbose_name": "Proveedor", "verbose_name_plural": "Proveedores"},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Role", "verbose_name_plural": "Roles"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
    ]
