# Generated by Django 4.1.3 on 2022-11-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_employee_options_alter_provider_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo_url",
            field=models.ImageField(
                default="http://cdn.onlinewebfonts.com/svg/img_569206.png",
                upload_to="profiles",
            ),
        ),
    ]
