# Generated by Django 4.1.3 on 2022-11-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_city_options_alter_location_options_and_more'),
        ('user', '0003_alter_user_photo_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': '1.3 Empleado', 'verbose_name_plural': '1.3 Empleados'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': '1.4 Proveedor', 'verbose_name_plural': '1.4 Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '1.2 Role', 'verbose_name_plural': '1.2 Roles'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '1.1 Usuario', 'verbose_name_plural': '1.1 Usuarios'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='charge',
        ),
        migrations.AlterField(
            model_name='employee',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nit',
            field=models.CharField(max_length=256, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='nit',
            field=models.CharField(max_length=256, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(verbose_name='¿Activo?'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='warehouse.city', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(max_length=20, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=80, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo_url',
            field=models.ImageField(default='http://cdn.onlinewebfonts.com/svg/img_569206.png', upload_to='profiles', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.role', verbose_name='Rol'),
        ),
    ]
