# Generated by Django 4.1.3 on 2022-11-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_alter_employee_options_alter_provider_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employee",
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "1.3 Empleados",
            },
        ),
        migrations.AlterModelOptions(
            name="provider",
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "1.4 Proveedores",
            },
        ),
        migrations.AlterModelOptions(
            name="role",
            options={"verbose_name": "Rol", "verbose_name_plural": "1.2 Roles"},
        ),
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuario", "verbose_name_plural": "1.1 Usuarios"},
        ),
        migrations.AlterField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=True, verbose_name="¿Activo?"),
        ),
        migrations.AlterField(
            model_name="user",
            name="document",
            field=models.CharField(blank=True, max_length=20, verbose_name="Documento"),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo_url",
            field=models.ImageField(
                default="media/profiles/default.png",
                upload_to="profiles/",
                verbose_name="Foto de perfil",
            ),
        ),
    ]
